name: tank_tracker_app

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0

  cupertino_icons: ^1.0.2
  

  english_words: ^4.0.0
  provider: ^6.1.2
  flutterfire_cli: ^1.0.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  

